languages : 
  ar:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/ar_f/ar_prompts2.flac
    text: "في الشهر الماضي، وصلنا إلى معلم جديد بمليارين من المشاهدات على قناتنا على يوتيوب."
  da:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/da_m1.flac
    text: "Sidste måned nåede vi en ny milepæl med to milliarder visninger på vores YouTube-kanal."
  de:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/de_f1.flac
    text: "Letzten Monat haben wir einen neuen Meilenstein erreicht: zwei Milliarden Aufrufe auf unserem YouTube-Kanal."
  el:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/el_m.flac
    text: "Τον περασμένο μήνα, φτάσαμε σε ένα νέο ορόσημο με δύο δισεκατομμύρια προβολές στο κανάλι μας στο YouTube."
  en:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/en_f1.flac
    text: "Last month, we reached a new milestone with two billion views on our YouTube channel."
  es:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/es_f1.flac
    text: "El mes pasado alcanzamos un nuevo hito: dos mil millones de visualizaciones en nuestro canal de YouTube."
  fi:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/fi_m.flac
    text: "Viime kuussa saavutimme uuden virstanpylvään kahden miljardin katselukerran kanssa YouTube-kanavallamme."
  fr:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/fr_f1.flac
    text: "Le mois dernier, nous avons atteint un nouveau jalon avec deux milliards de vues sur notre chaîne YouTube."
  he:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/he_m1.flac
    text: "בחודש שעבר הגענו לאבן דרך חדשה עם שני מיליארד צפיות בערוץ היוטיוב שלנו."
  hi:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/hi_f1.flac
    text: "पिछले महीने हमने एक नया मील का पत्थर छुआ: हमारे YouTube चैनल पर दो अरब व्यूज़।"
  it:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/it_m1.flac
    text: "Il mese scorso abbiamo raggiunto un nuovo traguardo: due miliardi di visualizzazioni sul nostro canale YouTube."
  ja:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/ja/ja_prompts1.flac
    text: "先月、私たちのYouTubeチャンネルで二十億回の再生回数という新たなマイルストーンに到達しました。"
  ko:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/ko_f.flac
    text: "지난달 우리는 유튜브 채널에서 이십억 조회수라는 새로운 이정표에 도달했습니다."
  ms:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/ms_f.flac
    text: "Bulan lepas, kami mencapai pencapaian baru dengan dua bilion tontonan di saluran YouTube kami."
  nl:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/nl_m.flac
    text: "Vorige maand bereikten we een nieuwe mijlpaal met twee miljard weergaven op ons YouTube-kanaal."
  no:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/no_f1.flac
    text: "Forrige måned nådde vi en ny milepæl med to milliarder visninger på YouTube-kanalen vår."
  pl:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/pl_m.flac
    text: "W zeszłym miesiącu osiągnęliśmy nowy kamień milowy z dwoma miliardami wyświetleń na naszym kanale YouTube."
  pt:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/pt_m1.flac
    text: "No mês passado, alcançámos um novo marco: dois mil milhões de visualizações no nosso canal do YouTube."
  ru:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/ru_m.flac
    text: "В прошлом месяце мы достигли нового рубежа: два миллиарда просмотров на нашем YouTube-канале."
  sv:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/sv_f.flac
    text: "Förra månaden nådde vi en ny milstolpe med två miljarder visningar på vår YouTube-kanal."
  sw:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/sw_m.flac
    text: "Mwezi uliopita, tulifika hatua mpya ya maoni ya bilioni mbili kweny kituo chetu cha YouTube."
  tr:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/tr_m.flac
    text: "Geçen ay YouTube kanalımızda iki milyar görüntüleme ile yeni bir dönüm noktasına ulaştık."
  zh:
    audio: https://storage.googleapis.com/chatterbox-demo-samples/mtl_prompts/zh_f2.flac
    text: "上个月，我们达到了一个新的里程碑。 我们的YouTube频道观看次数达到了二十亿次，这绝对令人难以置信。"